AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'views/*'
    - 'router.rb'

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatString:
  Enabled: false

Documentation:
  Enabled: false
