language: ruby
rvm:
- 2.1.5
services: mongodb
gemfile:
- Gemfile
addons:
  code_climate:
    repo_token: KOyQgfK5gLzK3rWMAi0vDQEU+rgdKmoVTpLU5mPLpcVGW0q6dv/jnlxezzZtB9tD5y3cNwN7Q7R3GrU6C6/ofz6cufzdAb9SuEGrU94I8olPnAJcgMJuxEBSy7Q4PDsJD8lKAbRhyjGtgwirXEGA5dSHJuPdFdjvH2M4iaSKp0shmgta6uGsb2SrWEbSmV9ydiyKqwht9mgZvLq3lEs69FK53QRICni87ZnB4k11O0VeAK3e56chsQS6MyAmuAJmS0E7fX2BFKYUABeX+KGUDAc73W66g9NjI5zJG0tMzq2TqMcrw7d1JQFb8GIVCTcbgV09h8SMRzB7lwP0wt7l1iBV0XOfZzI/EpO1xeWrqIsyMZHfIS+CHIJreQNQv5WxNvAZ4mSYOPpqPFILBv59URlXRInQwvjb0QJCsYGO6ClnWgPh2mU+UYQsNcO69v5l9RbyZRv+JUOCJHwrPRzusL/tpBmieYLy8ZiQBAx/wSWPDqa/plepx+Z6/N0SV2VEpKAIxE4qM0e12xtVy8Ll5CyNPURKloLvSD6yoL3390pLZ1mY2qESxIK/1mrhy7Mrgo//0yx3Ry697VnvNmN8FcHyUGUVvuyDnTGq5ZzQb9tinwwcEJxVNWd992QQuNd2ovyJh5bXchy6+CIOdvXk8L0QQFALC8XZ5aSq/oaBFKI=
